[font]
size = 8.0

normal = {family = "Courier Prime", style = "Regular"}
bold = {family = "Courier Prime", style = "Bold"}
italic = {family = "Courier Prime", style = "Italic"}

[cursor]
style = {shape = "Block", blinking = "on"}

[keyboard]
bindings = [
    {key = "Return", mods = "Super|Shift", action = "SpawnNewInstance"}
]

[general]
import = [ "/home/stanik/.config/alacritty/themes/alduin.toml" ]
