# vim:ft=kitty

## name:     Rusty Alduin
## author:   Your Name
## license:  MIT
## blurb:    A rusty, earthy color scheme matching Alduin Vim theme

# The basic colors
foreground              #dfdfaf
background              #000000
selection_foreground    #1c1c1c
selection_background    #000000

# Cursor colors
cursor                  #af8787
cursor_text_color       #000000

# URL underline color
url_color               #af875f

# Window border colors
active_border_color     #87875f
inactive_border_color   #4e4e4e
bell_border_color       #af5f5f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1c1c1c
active_tab_background   #af5f5f
inactive_tab_foreground #878787
inactive_tab_background #262626
tab_bar_background      #121212

# Marks colors
mark1_foreground #1c1c1c
mark1_background #af5f5f
mark2_foreground #1c1c1c
mark2_background #af875f
mark3_foreground #1c1c1c
mark3_background #87afaf

# The 16 terminal colors - adapted from your Vim theme's ansi colors

# basic colors
color0  #1c1c1c
color1  #af5f5f
color2  #87875f
color3  #dfaf87
color4  #878787
color5  #875f5f
color6  #87afaf
color7  #dfdfaf

# bright colors
color8  #878787
color9  #af5f5f
color10 #87875f
color11 #dfaf87
color12 #878787
color13 #875f5f
color14 #87afaf
color15 #dfdfaf
